### ISSUE TITLE
Support for VS2022?

### ISSUE THREAD

**Issue by Sjoerdsjoerd** [tetractic/ExceptionAnalyzers#4]
Are you going to support Visual Studio 2022?

**Comment by carlreinke** [comment]
Yeah, eventually.  The VS marketplace is supposed to add [support for uploading multiple VSIX to the same listing](https://docs.microsoft.com/en-us/visualstudio/extensibility/migration/update-visual-studio-extension?view=vs-2022#visual-studio-marketplace), which is what I've been waiting on, but it doesn't seem to be happening very quickly.

**Comment by carlreinke** [comment]
Seems like all the Microsoft-provided extensions are just publishing separate listings, so I guess it may be a while.

https://marketplace.visualstudio.com/items?itemName=carlreinke.ExceptionAnalyzers2022

**Comment by Sjoerdsjoerd** [comment]
> Seems like all the Microsoft-provided extensions are just publishing separate listings, so I guess it may be a while.
> 
> https://marketplace.visualstudio.com/items?itemName=carlreinke.ExceptionAnalyzers2022

The link does not seem to work:
![afbeelding](https://user-images.githubusercontent.com/19996084/151720523-78bfdcd8-bada-484a-8a8d-7afdb1a3d9de.png)

Could you check if you have published the listing?

**Comment by carlreinke** [comment]
Oops, looks like I forgot to hit the "Make Public" button.  It should be accessible now.
