### ISSUE TITLE
Option to disable ExceptionAnalyzers per Class or Project

### ISSUE THREAD

**Issue by DCourtel** [tetractic/ExceptionAnalyzers#5]
Can you provide a way to disable Exception Analyzers for all exceptions in a given Class or Project? It would be useful for test classes/projects. Maybe, this could be done using a #pragma directives.

Thanks.

**Comment by carlreinke** [comment]
I guess you're the Visual Studio extension?  The NuGet package is what you want for this case -- you can install the analyzer package to only the projects that you want to be analyzed.

**Comment by DCourtel** [comment]
Thank you for your swift answer. The NuGet package can fit my needs and I’m going to use it. But I still think a per Class or per Region option is still valuable and should be proposed.
